version: "3.9"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./artifacts:/app/artifacts
      - ./data:/app/data
    command: >
      /bin/sh -c "python -m rag.ingest && uvicorn app.main:app --host 0.0.0.0 --port 8000"
